const USER_ID=localStorage.getItem("sahayak_user_id")||crypto.randomUUID();localStorage.setItem("sahayak_user_id",USER_ID);
const $=id=>document.getElementById(id);
async function api(url,opts={}){const r=await fetch(url,{headers:{"Content-Type":"application/json",...(opts.headers||{})},...opts});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d}
function fields(){return{ name:$("name")?.value.trim()||"",guardian:$("guardian")?.value.trim()||"",age:$("age")?.value||"",category:$("category")?.value||"",income:$("income")?.value||"",education:$("education")?.value||"",state:$("state")?.value.trim()||"",district:$("district")?.value.trim()||""}}
function fill(p){Object.entries(p||{}).forEach(([k,v])=>{const e=$(k);if(e&&v!==undefined)e.value=v})}
async function getProfile(){try{return await api(`/api/profile/${USER_ID}`)}catch{return{}}}
async function askAI(){const q=$("question").value.trim();if(!q)return;const chat=$("chat");chat.insertAdjacentHTML("beforeend",`<div class="bubble user">${escapeHTML(q)}</div>`);$("question").value="";chat.scrollTop=chat.scrollHeight;try{const profile=await getProfile();const d=await api("/api/chat",{method:"POST",body:JSON.stringify({question:q,profile})});chat.insertAdjacentHTML("beforeend",`<div class="bubble bot">${escapeHTML(d.answer).replace(/\n/g,"<br>")}</div>`)}catch(e){chat.insertAdjacentHTML("beforeend",`<div class="bubble bot">Error: ${escapeHTML(e.message)}</div>`)}chat.scrollTop=chat.scrollHeight}
async function runOCR(){const f=$("file").files[0];if(!f)return alert("Please select a document image.");const fd=new FormData();fd.append("file",f);$("ocrStatus").textContent="Reading document with OCR...";try{const r=await fetch("/api/ocr",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"OCR failed");$("ocrText").value=d.text;fill(d.fields);$("ocrStatus").textContent=`OCR complete via ${d.provider}. Review the extracted information.`}catch(e){$("ocrStatus").textContent=e.message}}
async function recorrect(){const box=$("quality");box.textContent="Checking information...";try{const d=await api("/api/recorrect",{method:"POST",body:JSON.stringify({fields:fields()})});box.innerHTML=`<div class="panel"><h3>Data Quality: ${d.score}%</h3>${d.missing.length?`<p><b>Missing:</b> ${d.missing.join(", ")}</p>`:"<p>✓ Required fields are present.</p>"}${d.issues.map(x=>`<p>⚠ ${escapeHTML(x)}</p>`).join("")}<p>${escapeHTML(d.suggestion)}</p></div>`}catch(e){box.textContent=e.message}}
async function saveProfile(){try{const d=await api(`/api/profile/${USER_ID}`,{method:"PUT",body:JSON.stringify(fields())});alert("Profile saved successfully.");return d}catch(e){alert(e.message)}}
async function checkEligibility(){const p=fields();const box=$("results");box.innerHTML="<p>Checking possible matches...</p>";try{const d=await api("/api/eligibility",{method:"POST",body:JSON.stringify(p)});box.innerHTML=`<p class="muted">${escapeHTML(d.disclaimer)}</p>`+(d.matches.length?d.matches.map(x=>`<div class="panel match"><h3>${escapeHTML(x.name)}</h3><b>${escapeHTML(x.status)}</b><p>${escapeHTML(x.reason)}</p><p><b>Suggested documents:</b> ${x.documents.map(escapeHTML).join(", ")}</p><a href="${x.official}" target="_blank" rel="noopener">Visit official portal →</a></div>`).join(""):"<div class='panel'><h3>No prototype match found</h3><p>Try checking your details or consult the relevant official scheme portal.</p></div>`)}catch(e){box.textContent=e.message}}
async function addReminder(){const task=$("reminderTask").value.trim(),date=$("reminderDate").value;if(!task||!date)return alert("Enter a task and date.");try{await api(`/api/reminders/${USER_ID}`,{method:"POST",body:JSON.stringify({task,date})});$("reminderTask").value="";$("reminderDate").value="";loadReminders()}catch(e){alert(e.message)}}
async function loadReminders(){const box=$("reminders");if(!box)return;try{const d=await api(`/api/reminders/${USER_ID}`);box.innerHTML=d.length?"<hr><h4>Saved reminders</h4>"+d.map(x=>`<p>🔔 ${escapeHTML(x.task)}<br><small>${escapeHTML(x.date)}</small></p>`).join(""):""}catch{}}
async function init(){const p=await getProfile();if($("profileSummary"))$("profileSummary").innerHTML=p.name?`<b>${escapeHTML(p.name)}</b><p>${escapeHTML(p.state||"")} ${p.district?"· "+escapeHTML(p.district):""}</p><p>Category: ${escapeHTML(p.category||"Not set")}</p>`:"No saved profile yet. Use OCR + ReCorrect Engine to create one.";if($("name"))fill(p);loadReminders()}function escapeHTML(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}document.addEventListener("DOMContentLoaded",init);